# Generated by Django 3.2.18 on 2023-05-30 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0004_auto_20230530_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('idAvis', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name="Le nom de l'auteur de l'avis")),
                ('note', models.IntegerField(verbose_name='La note')),
                ('commentaire', models.CharField(max_length=100, verbose_name='Le commentaire')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applipizza.pizza')),
            ],
            options={
                'unique_together': {('pizza', 'commentaire')},
            },
        ),
    ]
