# Generated by Django 2.2.28 on 2023-05-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applipizza', '0005_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(verbose_name='Votre commentaire'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Votre nom'),
        ),
        migrations.AlterField(
            model_name='avis',
            name='note',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='La note'),
        ),
    ]
